select top 5 * from dbo.HighestGrossers
order by year asc


/*This  query syntax retrieves the first 5 movies and sorts them in ascending order by Year from the table (HighestGrossers) 
within the PortfolioProject database */


select * from dbo.HighestGrossers 
where [MPAA RATING] = 'PG-13' and [TOTAL IN 2019 DOLLARS] > 500000000

/* this query retrieves movies with a 'PG-13' rating and a revenue ("TOTAL IN 2019 DOLLARS") of over $500000000*/ 

select count(*) as Total_Number_of_movies 
from dbo.HighestGrossers
where year between 1990 and 1999 

/* This query counts the total amount of movies released between 1990 and 1999*/

select CAST ([TOTAL FOR YEAR] as int ) as New_Total
from dbo.HighestGrossers

/* This query converts the data type of the field ("TOTAL FOR YEAR") into an integer "Number" data type */


select * from dbo.HighestGrossers
where movie like 'B%' and [TOTAL FOR YEAR] > 200000000

/* This query returns the list of movies with the title beginning with "B", and with the total revenue for the year("TOTAL FOR YEAR") being greater than 200000000 */

select count(Movie) as Total_of_each_genre,
Genre

from dbo.HighestGrossers
where genre is not null 
group by genre
order by genre

/* this query counts the total number of movies in each genre/category, i.e Action, Adventure and Drama and groups the result by individual genre*/

select * from dbo.HighestGrossers
select *from dbo.TopGenres

select h.movie,
h.Genre,
h.Distributor,
t.[total gross],
t.[average gross],
t.[market share]
from dbo.HighestGrossers h inner join dbo.TopGenres t
on h.GENRE = t.GENRES
order by movie 

/* This query joins the corresoonding fields from two tables(HighestGrossers and TopGenres) by using the inner join function. it basically merges the data in the HighestGrossers table to the data in the TopGenres table */


select 
GENRE,
avg([Total in 2019 Dollars]) as Average_revenue_in_2019
from dbo.HighestGrossers
where GENRE is not null 
group by GENRE
order by GENRE

/* This query returns the average revenue generated by each Genre in 2019 */
